[[redirects]]
  from = "https://master--sleepy-wozniak-62f72d.netlify.com/*"
  to = "https://mulanbook.com/:splat"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "https://master--mulanbook.netlify.com/*"
  to = "https://mulanbook.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/mulan_joins_the_army"
  to = "https://mulanbook.com/pages/qing/mulan_joins_the_army_1903"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/fierce_and_filial_english_translation"
  to = "https://mulanbook.com/mulanbook"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/fierce_and_filial_english_translation_chapter_1"
  to = "https://mulanbook.com/mulanbook"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/fierce_and_filial_english_translation_chapter_2"
  to = "https://mulanbook.com/mulanbook"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/ming/legend-of-mulan-ming-dynasty.md"
  to = "https://mulanbook.com/mulanbook"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/ming/mulan-joins-the-army-xu-wei.md"
  to = "https://mulanbook.com/mulanbook"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/ming/women-generals.md"
  to = "https://mulanbook.com/mulanbook"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/northern-wei/ballad-of-mulan.md"
  to = "https://mulanbook.com/mulanbook"
  status = 301
  force = true












[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
