[[redirects]]
  from = "https://master--sleepy-wozniak-62f72d.netlify.com/*"
  to = "https://mulanbook.com/:splat"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "https://master--mulanbook.netlify.com/*"
  to = "https://mulanbook.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/mulan_joins_the_army"
  to = "https://mulanbook.com/pages/qing/mulan_joins_the_army_1903"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/fierce_and_filial_english_translation"
  to = "https://mulanbook.com/mulan-book"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/fierce_and_filial_english_translation_chapter_1"
  to = "https://mulanbook.com/mulan-book"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/fierce_and_filial_english_translation_chapter_2"
  to = "https://mulanbook.com/mulan-book"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/mulanbook"
  to = "https://mulanbook.com/mulan-book"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/ming/legend_of_mulan_ming_dynasty"
  to = "https://mulanbook.com/pages/ming/legend-of-mulan-ming-dynasty"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/ming/mulan_joins_the_army_xu_wei"
  to = "https://mulanbook.com/pages/ming/mulan-joins-the-army-xu-wei"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/ming/women_generals"
  to = "https://mulanbook.com/pages/ming/women-generals"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/northern_wei/ballad_of_mulan"
  to = "https://mulanbook.com/pages/northern-wei/ballad-of-mulan"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/overview/ask_question"
  to = "https://mulanbook.com/pages/overview/ask-question"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/overview/history_of_legend_of_mulan"
  to = "https://mulanbook.com/pages/overview/history-of-legend-of-mulan"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/overview/questions_about_mulans_legend_and_history"
  to = "https://mulanbook.com/pages/overview/questions-about-mulans-legend-and-history"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/overview/thank_you_question"
  to = "https://mulanbook.com/pages/overview/thank-you-question"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/post_imperial/disneys_live_action_mulan"
  to = "https://mulanbook.com/pages/post-imperial/disneys-live-action-mulan"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/post_imperial/disneys_mulan"
  to = "https://mulanbook.com/pages/post-imperial/disneys-mulan"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/post_imperial/lady_general_hua_mulan"
  to = "https://mulanbook.com/pages/post-imperial/lady-general-hua-mulan"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/post_imperial/legend_of_mulan_post_imperial_china"
  to = "https://mulanbook.com/pages/post-imperial/legend-of-mulan-post-imperial-china"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/post_imperial/mulan_joins_the_army_1939_film"
  to = "https://mulanbook.com/pages/post-imperial/mulan-joins-the-army-1939-film"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/post_imperial/mulan_rise_of_a_warrior"
  to = "https://mulanbook.com/pages/post-imperial/mulan-rise-of-a-warrior"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/post_imperial/the_woman_warrior"
  to = "https://mulanbook.com/pages/post-imperial/the-woman-warrior"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/biography_of_extraordinary_mulan"
  to = "https://mulanbook.com/pages/qing/complete-account-of-extraordinary-mulan"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/fierce_and_filial"
  to = "https://mulanbook.com/pages/qing/fierce-and-filial"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/legend_of_mulan_qing_dynasty"
  to = "https://mulanbook.com/pages/qing/legend-of-mulan-qing-dynasty"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/mulan_joins_the_army_1903"
  to = "https://mulanbook.com/pages/qing/mulan-joins-the-army-1903"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/qing/romance_of_sui_and_tang"
  to = "https://mulanbook.com/pages/qing/romance-of-sui-and-tang"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/tang/legend_of_mulan_tang_dynasty"
  to = "https://mulanbook.com/pages/tang/legend-of-mulan-tang-dynasty"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/tang/mulan_temple_du_mu"
  to = "https://mulanbook.com/pages/tang/mulan-temple-du-mu"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/tang/song_of_mulan"
  to = "https://mulanbook.com/pages/tang/song-of-mulan"
  status = 301
  force = true
[[redirects]]
  from = "https://mulanbook.com/pages/yuan/memorial_filial_general"
  to = "https://mulanbook.com/pages/yuan/memorial-filial-general"
  status = 301
  force = true
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
